#!/bin/bash
spt() {
    LOCK_FILE="/tmp/eww/spt_dashboard.lock"
    EWW_BIN="/usr/bin/eww"
    if [[ $1 == false ]]; then
        ${EWW_BIN} -c "$HOME/.config/eww" update spt_spawn="$1"
        sleep 0.1
        ${EWW_BIN} -c "$HOME/.config/eww" close spt
        rm "$LOCK_FILE"
    else
        ${EWW_BIN} -c "$HOME/.config/eww" open spt
        touch "$LOCK_FILE"
        ${EWW_BIN} -c "$HOME/.config/eww" update spt_spawn="$1"
    fi
}

if [[ "$1" = "spt" ]]; then
    spt "$2"
fi
