#!/bin/sh

symbol() {
    signal_strength="$1"
    if [ "$signal_strength" = "" ]; then
        echo -e "assets/signal-wifi-error-line.svg"
    elif [ "$signal_strength" -gt 0 ]; then
        echo -e "assets/signal-wifi-1-line.svg"
    elif [ "$signal_strength" -gt 30 ]; then
        echo -e "assets/signal-wifi-2-line.svg"
    elif [ "$signal_strength" -gt 50 ]; then
        echo -e "assets/signal-wifi-3-line.svg"
    else
        echo -e "assets/signal-wifi-line.svg"
    fi
}


name() {
nmcli | grep "^wlp" | sed 's/\ connected\ to\ /Connected to /g' | cut -d ':' -f2
}

[ "$1" = "icon" ] && symbol $(awk 'NR==3 {print $3}' /proc/net/wireless | sed "s/\.//") && exit
[ "$1" = "strength" ] && echo $(awk 'NR==3 {print $3}' /proc/net/wireless | sed "s/\.//") && exit
[ "$1" = "name" ] && name && exit
